export const UPDATE_ORIGINAL_DATA = 'UPDATE_ORIGINAL_DATA'

export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE'

export const UPDATE_RESULT_DATA = 'UPDATE_RESULT_DATA'

export const UPDATE_RESULT_STRDATA = 'UPDATE_RESULT_STRDATA'

export const UPDATE_RESULT_CPY = 'UPDATE_RESULT_CPY'